### ISSUE TITLE
Provide a way to access the https flavour

### ISSUE THREAD

**Issue by danielo515** [tobibeer/tw5-plugins#1]
Hello @tobibeer 

I really like all your plugins despite I don't use them very often.
I'm planning to include your plugin library as part of NoteSelf, if you agree.

I'm a bit concerned about how to configure your plugin library plugin to be served over https. I know that your plugin library is both available on http and https, however your plugin seems to be unable to detect when it is being served over https. So, if you navigate to **https:**//tobibeer.github.io/tw5-plugins your plugin library will try to acces the http version instead of the https causing a "mixing protocols error".

It would be amazing that your plugin detects it is being served over https and tries to access the https version of your library.

Thanks and regards.

**Comment by tobibeer** [comment]
Hi, @danielo515, I'm afraid loading a plugin library is handled by the core. So, if this needs fixing / configuration / detection... it needs to be fixed / configurable / detected by the core.

**Comment by tobibeer** [comment]
I just closed this, because it's not actionable here... not because I'm not interested in a fix. ;-)

**Comment by tobibeer** [comment]
@danielo515, would you be so kind as to open an issue for the core?

**Comment by danielo515** [comment]
Hello @tobibeer,

Which core do you mean? Tw5 core or the core of your plugin repo ?

What about my other question? The one about including your library

**Comment by tobibeer** [comment]
@danielo515, I mean the TW5 core and it's capabilities for loading a plugin library.

In other words, if you want to instruct anything to "load this library via https"... it's the TW5 core you need to address. There simply is no "Library plugin" or anything... it's simply just

1) a tiddler that allows you to register it
2) some bat or gulp script to generate the payload that the library mechanism can fetch as plugins
